### ISSUE TITLE
Is there a possibility to adjust menu of the voyager in code(migration, etc) ?

### ISSUE THREAD

**Issue by log57iii** [the-control-group/voyager#1637]
- Laravel Version: 5.4
- Voyager Version: last
- PHP Version: 5.6
- Database Driver & Version: mysql

### Description:
I don't need items like categories, posts, pages in the menu. I have to manually remove this items in front end after deploy my application. But I have others database tables, and again I must go to "menu builder" and adjust manyally all what I need. How to properly remove from migrations items above, and add mine? It's difficult to do without documentation. I have some erors when I try to do it by myself

**Comment by fletch3555** [comment]
There is documentation, but the documentation can't possibly cover every use-case.

For what you're asking for, just remove the entries you don't need from the `MenuItemsTableSeeder`
