### ISSUE TITLE
richTextBox showing Textarea instead of Editor after update to Laravel 7

### ISSUE THREAD

**Issue by nehasharma1997** [the-control-group/voyager#4966]
## Version information

 - Laravel: v7.13.0
 - Voyager: v1.4.1
 - PHP: 7.4.0

## Description

richTextBox showing Textarea instead of Editor after update to Laravel 7. It shows this in code:

<textarea class="form-control richTextBox" name="name" id="richtextname">    
</textarea>

## Steps To Reproduce
1. set richTextBox to a field and go to Create. It shows simple textarea, before updating to Laravel 7 in Laravel 6 it was working fine. 
## Expected behavior
It should show text editor.

**Comment by emptynick** [comment]
The textarea is perfectly fine.
Are there any error in your browsers console?

**Comment by nehasharma1997** [comment]
No there is no error in console. 
In Laravel 6 it shows :
`<div id="mceu_17" class="mce-tinymce mce-container mce-panel" hidefocus="1" tabindex="-1" role="application" style="visibility: hidden; border-width: 1px; width: 100%;"><div id="mceu_17-body" class="mce-container-body mce-stack-layout">`

now it shows
 `<textarea class="form-control richTextBox" name="name" id="richtextname"> </textarea>`

**Comment by MrCrayon** [comment]
Did you also update Voyager?
If yes:

- clear browser cache.
- check if you followed upgrade guide.
- update your views if you have custom views.

**Comment by nehasharma1997** [comment]
I have clear the cache. I added `"tcg/voyager": "^1.4.1",` in require and run `composer update`. I have added no custom views.

**Comment by MrCrayon** [comment]
DId you solve this one too clearing browser cache?
https://github.com/the-control-group/voyager/issues/4629#issuecomment-638287575

**Comment by nehasharma1997** [comment]
No, I have also try new browser but problem not solve yet. I think there is any problem in upgrading Laravel. I am new to Voyger and Laravel. How can I debug this ?

**Comment by MrCrayon** [comment]
Try searching in your browser elements for `additionalConfig`, you should have something like this:

![Schermata da 2020-06-04 06-19-43](https://user-images.githubusercontent.com/6875243/83714648-a62d1b80-a62b-11ea-81c6-f781be368ed4.png)

I don't from which version you updated but you need to follow all upgrade guides.
https://github.com/the-control-group/voyager/releases

**Comment by nehasharma1997** [comment]
I do not find any additionalConfig in elements, even I do not find it in my old browser in which Editor is working.
I have upgrade it from v1.3.2 to v1.4.1.
I am using richTextBox  in standard way i.e. I do not use any custom view or anything custom.

**Comment by MrCrayon** [comment]
It looks like your view is not updated. 
Make sure `php artisan cache:clear` is working properly, you might not have right permissions to clear cache and that command will fail silently.

**Comment by nehasharma1997** [comment]
`php artisan cache:clear` give  `Application cache cleared!` .

**Comment by MrCrayon** [comment]
`php artisan view:clear`

**Comment by nehasharma1997** [comment]
@MrCrayon thank you `php artisan view:clear` solve the problem.
