### ISSUE TITLE
How to use the belongs to many tagging

### ISSUE THREAD

**Issue by kgnfth** [the-control-group/voyager#5236]
How can i use the tagging system

i have a Post bread and i want to be able to select tags for the post
but i am not sure how to do it

Do i have to create a Tag bread first and then inside Post bread i dont know how to use the relations
should it be belongs to many tags or has many tags ?

**Comment by kgnfth** [comment]
@emptynick Why closing without explanation

**Comment by emptynick** [comment]
From the issue template:

> QUESTIONS ABOUT HOW TO USE VOYAGER SHOULD BE ASKED IN SLACK FIRST

And 

> The following information is required for bug reports.  Issues without it will be closed without response

**Comment by kgnfth** [comment]
okey sorry
